require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DayWorksController do

  # This should return the minimal set of attributes required to create a valid
  # DayWork. As you add validations to DayWork, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DayWorksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all day_works as @day_works" do
      day_work = DayWork.create! valid_attributes
      get :index, {}, valid_session
      assigns(:day_works).should eq([day_work])
    end
  end

  describe "GET show" do
    it "assigns the requested day_work as @day_work" do
      day_work = DayWork.create! valid_attributes
      get :show, {:id => day_work.to_param}, valid_session
      assigns(:day_work).should eq(day_work)
    end
  end

  describe "GET new" do
    it "assigns a new day_work as @day_work" do
      get :new, {}, valid_session
      assigns(:day_work).should be_a_new(DayWork)
    end
  end

  describe "GET edit" do
    it "assigns the requested day_work as @day_work" do
      day_work = DayWork.create! valid_attributes
      get :edit, {:id => day_work.to_param}, valid_session
      assigns(:day_work).should eq(day_work)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DayWork" do
        expect {
          post :create, {:day_work => valid_attributes}, valid_session
        }.to change(DayWork, :count).by(1)
      end

      it "assigns a newly created day_work as @day_work" do
        post :create, {:day_work => valid_attributes}, valid_session
        assigns(:day_work).should be_a(DayWork)
        assigns(:day_work).should be_persisted
      end

      it "redirects to the created day_work" do
        post :create, {:day_work => valid_attributes}, valid_session
        response.should redirect_to(DayWork.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved day_work as @day_work" do
        # Trigger the behavior that occurs when invalid params are submitted
        DayWork.any_instance.stub(:save).and_return(false)
        post :create, {:day_work => {}}, valid_session
        assigns(:day_work).should be_a_new(DayWork)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DayWork.any_instance.stub(:save).and_return(false)
        post :create, {:day_work => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested day_work" do
        day_work = DayWork.create! valid_attributes
        # Assuming there are no other day_works in the database, this
        # specifies that the DayWork created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DayWork.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => day_work.to_param, :day_work => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested day_work as @day_work" do
        day_work = DayWork.create! valid_attributes
        put :update, {:id => day_work.to_param, :day_work => valid_attributes}, valid_session
        assigns(:day_work).should eq(day_work)
      end

      it "redirects to the day_work" do
        day_work = DayWork.create! valid_attributes
        put :update, {:id => day_work.to_param, :day_work => valid_attributes}, valid_session
        response.should redirect_to(day_work)
      end
    end

    describe "with invalid params" do
      it "assigns the day_work as @day_work" do
        day_work = DayWork.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DayWork.any_instance.stub(:save).and_return(false)
        put :update, {:id => day_work.to_param, :day_work => {}}, valid_session
        assigns(:day_work).should eq(day_work)
      end

      it "re-renders the 'edit' template" do
        day_work = DayWork.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DayWork.any_instance.stub(:save).and_return(false)
        put :update, {:id => day_work.to_param, :day_work => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested day_work" do
      day_work = DayWork.create! valid_attributes
      expect {
        delete :destroy, {:id => day_work.to_param}, valid_session
      }.to change(DayWork, :count).by(-1)
    end

    it "redirects to the day_works list" do
      day_work = DayWork.create! valid_attributes
      delete :destroy, {:id => day_work.to_param}, valid_session
      response.should redirect_to(day_works_url)
    end
  end

end
